# This is a special configuration file to run tests on Travis-CI via
# GitHub notifications when changes are committed.
#
# See http://travis-ci.org/ for details


# We don't need sudo so can avoid the slower legacy container-based
# TravisCI infrastructure:
sudo: false

# We need Python 2.6 or 2.7 to run Galaxy (and some of the wrappers)
# but don't really care which.
language: python
python:
 - "2.6"
 - "2.7"

# We use the TravisCI build matrix to test two versions of Galaxy,
# the current development branch (dev), and as a proxy for the
# current stable release, master:
#
env:
 - GALAXY_BRANCH=dev
 - GALAXY_BRANCH=master

# Planemo Lint
# ============
#
# Planemo can be run to check tools separately from Galaxy, and this
# is fast so we do it *before* the slow process of installing Galaxy
# and running the tool tests.
#
#
# Installing Galaxy
# =================
#
# Before installing our Galaxy wrappers, we need to install Galaxy.
#
# Galaxy used to be developed in hg using BitBucket, but cloning with
# hg or getting a specific revision with wget was quite slow. Using
# git clone with a mirror on GitHub was faster, while getting the
# latest revision with wget from GitHub was even faster.
#
# We therefore use wget with the new official Galaxy repository on
# GitHub, https://github.com/galaxyproject/galaxy
#
#
# Installing Tool Dependencies
# ============================
#
# We grab Galaxy, and will later make configuration changes specifically
# for testing our tools. Otherwise we use the default settings such as
# running with an SQLite database.
#
# We also need to install our tool dependencies, e.g. MIRA binaries
# which we will do via "planemo dependency_script" rather than via a
# (local) Galaxy Tool Shed. Note we need to install the different
# versions of MIRA into separate directories as the binary filenames
# clash otherwise. Although the tool_dependencies.xml files do define
# unique environment variables $MIRA3, $MIRA4 and $MIRA4_9 at the moment
# the MIRA 3.4 wrapper only looks at $PATH and therefore this must be
# installed last.
#

before_install:
 - echo "Using planemo lint to check for obvious tool errors"
 - pip install planemo
 - ./planemo_ci_find.py
 - ./planemo_ci_lint.py
 - ./planemo_ci_diff.py
 - echo "Fixing permissions on Python eggs cache folder"
 - mkdir -p "$HOME/.python-eggs"
 - chmod 700 "$HOME/.python-eggs"
 - export DOWNLOAD_CACHE=/tmp/download_cache && mkdir $DOWNLOAD_CACHE
 - echo "Downloading and setting up MIRA 4.0..."
 - export INSTALL_DIR=/tmp/dep_install_mira_4_0 && mkdir $INSTALL_DIR
 - planemo dependency_script ${TRAVIS_BUILD_DIR}/packages/package_mira_4_0_2
 - bash dep_install.sh
 - source env.sh
 - echo "Downloading and setting up MIRA 4.9..."
 - export INSTALL_DIR=/tmp/dep_install_mira_4_9 && mkdir $INSTALL_DIR
 - planemo dependency_script ${TRAVIS_BUILD_DIR}/packages/package_mira_4_9_5
 - bash dep_install.sh
 - source env.sh
 - echo "Downloading and setting up MIRA 3.4..."
 - export INSTALL_DIR=/tmp/dep_install_mira_3_4 && mkdir $INSTALL_DIR
 - planemo dependency_script ${TRAVIS_BUILD_DIR}/packages/package_mira_3_4_1_1
 - bash dep_install.sh
 - source env.sh
 - echo "Installing samtools..."
 - cd ${TRAVIS_BUILD_DIR} && mkdir samtools && cd samtools
 - wget http://depot.galaxyproject.org/package/linux/x86_64/samtools/samtools-0.1.19-Linux-x86_64.tgz
 - tar -zxvf samtools-0.1.19-Linux-x86_64.tgz
 - export PATH=$PWD/bin/:$PATH
 - echo "Fetching Galaxy ${GALAXY_BRANCH} branch..."
 - cd ${TRAVIS_BUILD_DIR}
 - wget https://codeload.github.com/galaxyproject/galaxy/tar.gz/${GALAXY_BRANCH}
 - tar -zxvf ${GALAXY_BRANCH} | tail
 - cd galaxy-${GALAXY_BRANCH}
 - pip install requests 

# Configuring tools within Galaxy
# ===============================
#
# We setup a minimal tool_conf.xml and/or tool_conf.xml.sample file to
# get Galaxy to just test our tools, rather than via a (local) Galaxy
# Tool Shed.
#
# TODO - GALAXY_TEST_TOOL_CONF environment variable rather than symlink?
#
# We setup our tools under the Galaxy tool folder by using symlinks.
# TODO - Restructure this to auto-update in future when add folders?
#
# We setup our datatypes by adding mira.py to the Galaxy library, and
# adding an import in lib/galaxy/datatypes/registry.py, and replacing
# the datatypes_conf.xml file.
#
# We setup our sample data in the Galaxy test-data folder by copying them
# (using symlinks might be faster?)
#
# Galaxy now provides a startup script to setup all the sample files,
# and fetch egg/wheel Python dependecies etc.


install:
 - cd ${TRAVIS_BUILD_DIR}/galaxy-${GALAXY_BRANCH}
 - export GALAXY_TEST_UPLOAD_ASYNC=false
 - export GALAXY_TEST_DB_TEMPLATE=https://github.com/jmchilton/galaxy-downloads/raw/master/db_gx_rev_0127.sqlite
 - ln -s ${TRAVIS_BUILD_DIR}/.travis.tool_conf.xml tool_conf.xml
 - rm -f config/tool_conf.xml.sample
 - ln -s ${TRAVIS_BUILD_DIR}/.travis.tool_conf.xml config/tool_conf.xml.sample
 - for i in $( ls ${TRAVIS_BUILD_DIR}/tools/ ); do ln -s ${TRAVIS_BUILD_DIR}/tools/$i/ tools/$i ; done
 - ln -s ${TRAVIS_BUILD_DIR}/datatypes/mira_datatypes/mira.py lib/galaxy/datatypes/mira.py
 - ln -s ${TRAVIS_BUILD_DIR}/.travis.datatypes_conf.xml datatypes_conf.xml
 - cp ${TRAVIS_BUILD_DIR}/test-data/* test-data/
 - bash scripts/common_startup.sh --skip-venv --dev-wheels
 - cp ${TRAVIS_BUILD_DIR}/planemo_ci_* .


# Testing tools in Galaxy
# =======================
#
# Having setup our Galaxy with a minimal tool_conf.xml / tool_conf.xml.sample
# we call planemo to test those tools which passed linting and have updates.

script:
 - ./planemo_ci_test.py
 - ./planemo_ci_report.py


# Pushing updated tested tools to Tool Shed
# =========================================
#
# Should we deploy working tools even if some tools failed?
# If so, could use after_script here
#
# Note to avoid any race conditions between the build matrix
# jobs, restrict the Test Tool Shed update to one run only:

after_success:
 - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $GALAXY_BRANCH == 'master' ]]; then ./planemo_ci_update.py; fi"

#The email defaults are too talkative while we're getting Travis working nicely.
notifications:
  email: false
