name: mira4_9_mirabait
owner: peterjc
homepage_url: http://chevreux.org/projects_mira.html
remote_repository_url: https://github.com/peterjc/galaxy_mira/tree/master/tools/mira4_9
description: mirabait from MIRA 4.9 assembler suite
long_description: |
  Wrapper for mirabait functionality of assembly tool MIRA 4.9, k-mer based
  filtering of sequence files supporting paired reads.
categories:
- Assembly
- Fastq Manipulation
- Fasta Manipulation
type: unrestricted
include:
- strip_components: 3
  source:
  - ../../../tools/mira4_9/mirabait/README.rst
  - ../../../tools/mira4_9/mirabait/mira4_9_mirabait.xml
  - ../../../tools/mira4_9/mirabait/repository_dependencies.xml
  - ../../../tools/mira4_9/mirabait/tool_dependencies.xml
  - ../../../test-data/tvc_bait.fasta
  - ../../../test-data/tvc_mini.fastq
  - ../../../test-data/tvc_mini_bait_pos.fastq
  - ../../../test-data/tvc_mini_bait_pos_case.fastq
  - ../../../test-data/tvc_mini_bait_strict.fastq
  - ../../../test-data/tvc_mini_bait_strict_case.fastq
  - ../../../test-data/tvc_mini_bait_neg.fastq
  - ../../../test-data/tvc_mini_bait_neg_case.fastq
