name: mira4_assembler
owner: peterjc
homepage_url: https://github.com/peterjc/pico_galaxy/tree/master/tools/mira4_assembler
remote_repository_url: https://github.com/peterjc/pico_galaxy/tree/master/tools/mira4_assembler
description: MIRA 4.0 assembler
long_description: |
  Wrapper for core functionality of assembly tool MIRA 4.0. Accepts data
  from Solexa/Illumina, Roche 454, Ion Torrent, PacBio and Sanger capillary
  sequencing. The key MIRA output files are captured, but the other files are
  deleted when the job finishes.
categories:
- Assembly
- Next Gen Mappers
type: unrestricted
include:
- strip_components: 2
  source:
  - ../../test-data/U13small_m.fastq
  - ../../test-data/U13small_m.mira4_de_novo.fasta
  - ../../test-data/ecoli.fastq
  - ../../test-data/ecoli.mira4_de_novo.fasta
  - ../../test-data/empty_file.dat
  - ../../test-data/header.mira
  - ../../test-data/tvc_mini.fastq
  - ../../test-data/tvc_contigs.fasta
  - ../../test-data/tvc_map_ref_strain.fasta
  - ../../test-data/tvc_map_same_strain.fasta
  - ../../test-data/tvc_bait.fasta
  - ../../test-data/tvc_mini_bait_neg.fastq
  - ../../test-data/tvc_mini_bait_pos.fastq
  - ../../test-data/tvc_mini_bait_strict.fastq
  - ../../tools/mira4_assembler/README.rst
  - ../../tools/mira4_assembler/mira4.py
  - ../../tools/mira4_assembler/mira4_bait.py
  - ../../tools/mira4_assembler/mira4_convert.py
  - ../../tools/mira4_assembler/mira4_de_novo.xml
  - ../../tools/mira4_assembler/mira4_make_bam.py
  - ../../tools/mira4_assembler/mira4_mapping.xml
  - ../../tools/mira4_assembler/mira4_validator.py
  - ../../tools/mira4_assembler/repository_dependencies.xml
  - ../../tools/mira4_assembler/tool_dependencies.xml
