name: mira4_assembler
owner: peterjc
homepage_url: https://github.com/peterjc/pico_galaxy/tools/mira4_assembler
remote_repository_url: https://github.com/peterjc/pico_galaxy/tools/mira4_assembler
description: MIRA 4.0 assembler
long_description: |
  Wrapper for core functionality of assembly tool MIRA 4.0.

  Accepts data from Solexa/Illumina, Roche 454, Ion Torrent, PacBio and Sanger capillary
  sequencing.

  The key MIRA output files are captured, but the other files are deleted when the
  job finishes.
categories:
- Assembly
- Next Gen Mappers
type: unrestricted
