name: package_mira_4_9_5
owner: peterjc
homepage_url: http://chevreux.org/projects_mira.html
remote_repository_url: https://github.com/peterjc/pico_galaxy/tree/master/packages/package_mira_4_9_5
description: MIRA assembler v4.9.5 (development release)
long_description: |
  Downloads MIRA v4.9.5 from Sourceforge, requesting Bastien's precompiled binaries
  for 64 bit (x86_64) Linux. Currently the Mac OS X binaries are not available.

  Other platforms where compilation from source would be required (e.g. 32 bit Linux)
  are not supported by this automated installation script.

  http://chevreux.org/projects_mira.html
  http://sourceforge.net/projects/mira-assembler/
categories:
- Tool Dependency Packages
type: tool_dependency_definition
